### ISSUE TITLE
update 'download' flow to redirect to PANW download site

### ISSUE THREAD

**Issue by morellonet** [twistlock/docs#197]
After removing the auth from docs.twistlock.com, we need to update the copy around the download flows to make it clear that customers can find links on the official PANW download site.  Currently, clicking on "Download the Software" takes users to the latest release notes (https://docs.twistlock.com/docs/releases/release-information/latest.html) but there's no copy there to make it clear that the actual downloads are only available on the download center.

**Comment by iansk** [comment]
Added an article at the top that describes the two different ways you can get our release tarball.

https://docs.twistlock.com/docs/releases/release-information/download.html

Also, made a ton of additional changes so that every flow provides the right download instructions. See the PR here:

https://github.com/twistlock/docs/pull/201

Fixed, closing.
